<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Attribute_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get attribute by id
     */
    function get_attribute($id)
    {
        return $this->db->get_where('attributes',array('id'=>$id))->row_array();
    }

    /*
    * Get attribute by id
    */
    function get_attribute_by_title($title)
    {
        $this->db->order_by('title', 'DESC');
        $this->db->like("title", $title);
        return $this->db->get('attributes')->result_array();
    }


    /*
     * Get all attributes count
     */
    function get_all_attributes_count()
    {
        $this->db->from('attributes');
        return $this->db->count_all_results();
    }


    /*
   * Get essential attributes
   */
    function get_essential_attributes()
    {

        return $this->db->get_where('attributes',array('is_essential'=>1))->result_array();
    }


    /*
     * Get all attributes
     */
    function get_all_attributes($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('attributes')->result_array();
    }
        
    /*
     * function to add new attribute
     */
    function add_attribute($params)
    {
        $this->db->insert('attributes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update attribute
     */
    function update_attribute($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('attributes',$params);
    }
    
    /*
     * function to delete attribute
     */
    function delete_attribute($id)
    {
        return $this->db->delete('attributes',array('id'=>$id));
    }
}
