<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Contact_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get contact by id
     */
    function get_contact($id)
    {
        return $this->db->get_where('contacts',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all contacts count
     */
    function get_all_contacts_count()
    {
        $this->db->from('contacts');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all contacts
     */
    function get_all_contacts($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('contacts')->result_array();
    }
        
    /*
     * function to add new contact
     */
    function add_contact($params)
    {
        $this->db->insert('contacts',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update contact
     */
    function update_contact($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('contacts',$params);
    }
    
    /*
     * function to delete contact
     */
    function delete_contact($id)
    {
        return $this->db->delete('contacts',array('id'=>$id));
    }
}
