<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Gallery_slider_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get gallery_slider by id
     */
    function get_gallery_slider($id)
    {
        return $this->db->get_where('gallery_slider',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all gallery_slider count
     */
    function get_all_gallery_slider_count()
    {
        $this->db->from('gallery_slider');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all gallery_slider
     */
    function get_all_gallery_slider($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('gallery_slider')->result_array();
    }
        
    /*
     * function to add new gallery_slider
     */
    function add_gallery_slider($params)
    {
        $this->db->insert('gallery_slider',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update gallery_slider
     */
    function update_gallery_slider($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('gallery_slider',$params);
    }
    
    /*
     * function to delete gallery_slider
     */
    function delete_gallery_slider($id)
    {
        return $this->db->delete('gallery_slider',array('id'=>$id));
    }
}
