<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Item_ingrident_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get item_ingrident by id
     */
    function get_item_ingrident($id)
    {
        return $this->db->get_where('item_ingridents',array('id'=>$id))->row_array();
    }



    function get_item_ingrident_by_item($id)
    {


        return $this->db->get_where('item_ingridents',array('item_id'=>$id))->result_array();
    }
    
    /*
     * Get all item_ingridents count
     */
    function get_all_item_ingridents_count()
    {
        $this->db->from('item_ingridents');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all item_ingridents
     */
    function get_all_item_ingridents($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('item_ingridents')->result_array();
    }
        
    /*
     * function to add new item_ingrident
     */
    function add_item_ingrident($params)
    {
        $this->db->insert('item_ingridents',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update item_ingrident
     */
    function update_item_ingrident($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('item_ingridents',$params);
    }
    
    /*
     * function to delete item_ingrident
     */
    function delete_item_ingrident($id)
    {
        return $this->db->delete('item_ingridents',array('id'=>$id));
    }
}
