<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Testominal_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get testominal by id
     */
    function get_testominal($id)
    {
        return $this->db->get_where('testominals',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all testominals count
     */
    function get_all_testominals_count()
    {
        $this->db->from('testominals');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all testominals
     */
    function get_all_testominals($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('testominals')->result_array();
    }
        
    /*
     * function to add new testominal
     */
    function add_testominal($params)
    {
        $this->db->insert('testominals',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update testominal
     */
    function update_testominal($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('testominals',$params);
    }
    
    /*
     * function to delete testominal
     */
    function delete_testominal($id)
    {
        return $this->db->delete('testominals',array('id'=>$id));
    }
}
