<?php

/**
 * Created by PhpStorm.
 * User: Alber Nahhas
 * Date: 11/20/2017
 * Time: 4:15 PM
 */
class Category_modelTest extends PHPUnit_Framework_TestCase
{


    public function test()
    {
    }

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

}
