<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Home_slider_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get home_slider by id
     */
    function get_home_slider($id)
    {
        return $this->db->get_where('home_slider',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all home_slider count
     */
    function get_all_home_slider_count()
    {
        $this->db->from('home_slider');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all home_slider
     */
    function get_all_home_slider($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('home_slider')->result_array();
    }
        
    /*
     * function to add new home_slider
     */
    function add_home_slider($params)
    {
        $this->db->insert('home_slider',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update home_slider
     */
    function update_home_slider($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('home_slider',$params);
    }
    
    /*
     * function to delete home_slider
     */
    function delete_home_slider($id)
    {
        return $this->db->delete('home_slider',array('id'=>$id));
    }
}
