<?php

/*
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Item_category_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    /*
     * Get item_category by id
     */
    function get_item_category($id)
    {
        return $this->db->get_where('item_categories', array('id' => $id))->row_array();
    }


    function get_item_category_by_item($id)
    {

        return $this->db->query('SELECT categories.id,categories.title,item_categories.item_id  from categories
 INNER JOIN item_categories ON categories.id=item_categories.cat_id 
WHERE categories.id IN (SELECT  cat_id FROM `item_categories` where item_id=' . $id . ')
AND item_categories.item_id =' . $id)->result_array();

    }

    /*
     * Get all item_categories count
     */
    function get_all_item_categories_count()
    {
        $this->db->from('item_categories');
        return $this->db->count_all_results();
    }

    /*
     * Get all item_categories
     */
    function get_all_item_categories($params = array())
    {
        $this->db->order_by('id', 'desc');
        if (isset($params) && !empty($params)) {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('item_categories')->result_array();
    }

    /*
     * function to add new item_category
     */
    function add_item_category($params)
    {
        $this->db->insert('item_categories', $params);
        return $this->db->insert_id();
    }

    /*
     * function to update item_category
     */
    function update_item_category($id, $params)
    {
        $this->db->where('id', $id);
        return $this->db->update('item_categories', $params);
    }

    /*
     * function to delete item_category
     */
    function delete_item_category($id)
    {
        return $this->db->delete('item_categories', array('id' => $id));
    }
}
