<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Member_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get member by id
     */
    function get_member($id)
    {
        return $this->db->get_where('members',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all members
     */
    function get_all_members()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('members')->result_array();
    }
        
    /*
     * function to add new member
     */
    function add_member($params)
    {
        $this->db->insert('members',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update member
     */
    function update_member($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('members',$params);
    }
    
    /*
     * function to delete member
     */
    function delete_member($id)
    {
        return $this->db->delete('members',array('id'=>$id));
    }
}
