<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Program_order_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get program_order by id
     */
    function get_program_order($id)
    {
        return $this->db->get_where('program_orders',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all program_orders count
     */
    function get_all_program_orders_count()
    {
        $this->db->from('program_orders');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all program_orders
     */
    function get_all_program_orders($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('program_orders')->result_array();
    }
        
    /*
     * function to add new program_order
     */
    function add_program_order($params)
    {
        $this->db->insert('program_orders',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update program_order
     */
    function update_program_order($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('program_orders',$params);
    }
    
    /*
     * function to delete program_order
     */
    function delete_program_order($id)
    {
        return $this->db->delete('program_orders',array('id'=>$id));
    }
}
