<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Program_item_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get program_item by id
     */
    function get_program_item($id)
    {
        return $this->db->get_where('program_item',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all program_item count
     */
    function get_all_program_item_count()
    {
        $this->db->from('program_item');
        return $this->db->count_all_results();
    }

    function get_program_item_by_program($id)
    {


        return $this->db->query('SELECT items.id,items.title,items.sub_title,items.image,(select title from Categories where id=items.cat_id) as catname,program_item.day,program_item.meal
from items INNER JOIN program_item ON items.id=program_item.item_id
WHERE items.id IN (SELECT items.id FROM `program_item` where program_id=' . $id . ')
AND program_item.program_id =' . $id)->result_array();

    }

    /*
     * Get all program_item
     */
    function get_all_program_item($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('program_item')->result_array();
    }





    /*
     * function to add new program_item
     */
    function add_program_item($params)
    {
        $this->db->insert('program_item',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update program_item
     */
    function update_program_item($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('program_item',$params);
    }
    
    /*
     * function to delete program_item
     */
    function delete_program_item($id)
    {
        return $this->db->delete('program_item',array('id'=>$id));
    }
}
