<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Calendar extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Calendar_model');
    }

    /*
     * Listing of calendar
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('calendar/index?');
        $config['total_rows'] = $this->Calendar_model->get_all_calendar_count();
        $this->pagination->initialize($config);

        $data['calendar'] = $this->Calendar_model->get_all_calendar($params);

        $data['_view'] = 'calendar/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new calendar
     */
    function add()
    {
        if(isset($_POST) && count($_POST) > 0)
        {

            $config = array(
                'upload_path' => "./uploads/",
                'allowed_types' => "gif|jpg|png|jpeg|pdf",
                'overwrite' => TRUE,
                'max_size' => "2048000", // Can be set to particular file size , here it is 2 MB(2048 Kb)
                'max_height' => "2000",
                'max_width' => "3000",
                'encrypt_name' => FALSE
            );
            $this->load->library('upload', $config);
            if (  $this->upload->do_upload('image'))
            {
                $data = array('upload_data' => $this->upload->data());

                
            }
            else
            {

                $error = array('error' => $this->upload->display_errors());
                echo print_r($error);
            }

            $params = array(
                'title' => $this->input->post('title'),
                'image' => isset($_FILES['image'])?$_FILES['image']['name']:"default.jpg",
                'text' => $this->input->post('text'),
                'date' => $this->input->post('date'),
            );

            $calendar_id = $this->Calendar_model->add_calendar($params);
            redirect('calendar/index');
        }
        else
        {
            $data['_view'] = 'calendar/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a calendar
     */
    function edit($id)
    {
        // check if the calendar exists before trying to edit it
        $data['calendar'] = $this->Calendar_model->get_calendar($id);
        $image=$data['calendar']['image'];

        $new_upload=false;
        if(isset($data['calendar']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {

                if(isset($_FILES['image']) && $_FILES['image']['error'] != 4) {
                    $config = array(
                        'upload_path' => "./uploads/",
                        'allowed_types' => "gif|jpg|png|jpeg|pdf",
                        'overwrite' => TRUE,
                        'max_size' => "2048000", // Can be set to particular file size , here it is 2 MB(2048 Kb)
                        'max_height' => "2000",
                        'max_width' => "3000",
                        'encrypt_name' => FALSE
                    );
                    $this->load->library('upload', $config);
                    if ($this->upload->do_upload('image')) {
                        $data = array('upload_data' => $this->upload->data());
                        $new_upload=true;
                    } else {

                        $error = array('error' => $this->upload->display_errors());
                        echo print_r($error);
                    }
                }


                $params = array(
                    'title' => $this->input->post('title'),
                    'image' => ($new_upload==true)?$_FILES['image']['name']: $image,
                    'text' => $this->input->post('text'),
                    'date' => $this->input->post('date'),
                );

                $this->Calendar_model->update_calendar($id,$params);
                redirect('calendar/index');
            }
            else
            {
                $data['_view'] = 'calendar/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The calendar you are trying to edit does not exist.');
    }

    /*
     * Deleting calendar
     */
    function remove($id)
    {
        $calendar = $this->Calendar_model->get_calendar($id);

        // check if the calendar exists before trying to delete it
        if(isset($calendar['id']))
        {
            $this->Calendar_model->delete_calendar($id);
            redirect('calendar/index');
        }
        else
            show_error('The calendar you are trying to delete does not exist.');
    }

}

