<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Contact extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Contact_model');
    } 

    /*
     * Listing of contacts
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('contact/index?');
        $config['total_rows'] = $this->Contact_model->get_all_contacts_count();
        $this->pagination->initialize($config);

        $data['contacts'] = $this->Contact_model->get_all_contacts($params);
        
        $data['_view'] = 'contact/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new contact
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'first_name' => $this->input->post('first_name'),
				'email' => $this->input->post('email'),
				'phone' => $this->input->post('phone'),
				'last_name' => $this->input->post('last_name'),
				'text' => $this->input->post('text'),
            );
            
            $contact_id = $this->Contact_model->add_contact($params);
            redirect('contact/index');
        }
        else
        {            
            $data['_view'] = 'contact/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a contact
     */
    function edit($id)
    {   
        // check if the contact exists before trying to edit it
        $data['contact'] = $this->Contact_model->get_contact($id);
        
        if(isset($data['contact']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'first_name' => $this->input->post('first_name'),
					'email' => $this->input->post('email'),
					'phone' => $this->input->post('phone'),
					'last_name' => $this->input->post('last_name'),
					'text' => $this->input->post('text'),
                );

                $this->Contact_model->update_contact($id,$params);            
                redirect('contact/index');
            }
            else
            {
                $data['_view'] = 'contact/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The contact you are trying to edit does not exist.');
    } 

    /*
     * Deleting contact
     */
    function remove($id)
    {
        $contact = $this->Contact_model->get_contact($id);

        // check if the contact exists before trying to delete it
        if(isset($contact['id']))
        {
            $this->Contact_model->delete_contact($id);
            redirect('contact/index');
        }
        else
            show_error('The contact you are trying to delete does not exist.');
    }
    
}
