<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->user = $this->session->userdata('logged_in');

    }

    function index()
    {
        $data['_view'] = 'dashboard';

//        if ( ! $this->user)
//        {
////            if (current_url() != base_url()) {
//
//            redirect('index.html');
//
////            }
//        }



        $this->load->view('layouts/main',$data);
    }
}
