<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Home_slider extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Home_slider_model');
        $this->load->helper(array('form', 'url'));
    } 

    /*
     * Listing of home_slider
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('home_slider/index?');
        $config['total_rows'] = $this->Home_slider_model->get_all_home_slider_count();
        $this->pagination->initialize($config);

        $data['home_slider'] = $this->Home_slider_model->get_all_home_slider($params);
        
        $data['_view'] = 'home_slider/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new home_slider
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {

            $config = array(
                'upload_path' => "./uploads/",
                'allowed_types' => "gif|jpg|png|jpeg|pdf",
                'overwrite' => TRUE,
                'max_size' => "2048000", // Can be set to particular file size , here it is 2 MB(2048 Kb)
                'max_height' => "2000",
                'max_width' => "3000"
            );
            $this->load->library('upload', $config);
            if (  $this->upload->do_upload('image'))
            {
                $data = array('upload_data' => $this->upload->data());

           
            }
            else
            {

                $error = array('error' => $this->upload->display_errors());
                // echo print_r($error);
            }

            $params = array(
				'title' => $this->input->post('title'),
                'image' => isset($_FILES['image'])?$_FILES['image']['name']:"default.jpg",
				'text' => $this->input->post('text'),

            );
            
            $home_slider_id = $this->Home_slider_model->add_home_slider($params);
            redirect('home_slider/index');
        }
        else
        {            
            $data['_view'] = 'home_slider/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a home_slider
     */
    function edit($id)
    {   
        // check if the home_slider exists before trying to edit it
        $data['home_slider'] = $this->Home_slider_model->get_home_slider($id);

        $image=$data['home_slider']['image'];

        $new_upload=false;

        if(isset($data['home_slider']['id']))
        {

            if(isset($_POST) && count($_POST) > 0)     
            {

                if(isset($_FILES['image'])) {
                    $config = array(
                        'upload_path' => "./uploads/",
                        'allowed_types' => "gif|jpg|png|jpeg|pdf",
                        'overwrite' => TRUE,
                        'max_size' => "2048000", // Can be set to particular file size , here it is 2 MB(2048 Kb)
                        'max_height' => "2000",
                        'max_width' => "3000"
                    );
                    $this->load->library('upload', $config);
                    if ($this->upload->do_upload('image')) {
                        $data = array('upload_data' => $this->upload->data());
                        $new_upload=true;
                    } else {

                        $error = array('error' => $this->upload->display_errors());
                        echo print_r($error);
                    }
                }


                $params = array(
					'title' => $this->input->post('title'),
                    'image' => ($new_upload==true)?$_FILES['image']['name']: $image,
					'text' => $this->input->post('text'),
                );

                $this->Home_slider_model->update_home_slider($id,$params);            
                redirect('home_slider/index');
            }
            else
            {
                $data['_view'] = 'home_slider/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The home_slider you are trying to edit does not exist.');
    } 

    /*
     * Deleting home_slider
     */
    function remove($id)
    {
        $home_slider = $this->Home_slider_model->get_home_slider($id);

        // check if the home_slider exists before trying to delete it
        if(isset($home_slider['id']))
        {
            $this->Home_slider_model->delete_home_slider($id);
            redirect('home_slider/index');
        }
        else
            show_error('The home_slider you are trying to delete does not exist.');
    }
    
}
