<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Item_ingrident extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Item_ingrident_model');
    } 

    /*
     * Listing of item_ingridents
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('item_ingrident/index?');
        $config['total_rows'] = $this->Item_ingrident_model->get_all_item_ingridents_count();
        $this->pagination->initialize($config);

        $data['item_ingridents'] = $this->Item_ingrident_model->get_all_item_ingridents($params);
        
        $data['_view'] = 'item_ingrident/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new item_ingrident
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'item_id' => $this->input->post('item_id'),
				'text' => $this->input->post('text'),
            );
            
            $item_ingrident_id = $this->Item_ingrident_model->add_item_ingrident($params);
            redirect('item_ingrident/index');
        }
        else
        {
			$this->load->model('Item_model');
			$data['all_items'] = $this->Item_model->get_all_items();
            
            $data['_view'] = 'item_ingrident/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a item_ingrident
     */
    function edit($id)
    {   
        // check if the item_ingrident exists before trying to edit it
        $data['item_ingrident'] = $this->Item_ingrident_model->get_item_ingrident($id);
        
        if(isset($data['item_ingrident']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'item_id' => $this->input->post('item_id'),
					'text' => $this->input->post('text'),
                );

                $this->Item_ingrident_model->update_item_ingrident($id,$params);            
                redirect('item_ingrident/index');
            }
            else
            {
				$this->load->model('Item_model');
				$data['all_items'] = $this->Item_model->get_all_items();

                $data['_view'] = 'item_ingrident/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The item_ingrident you are trying to edit does not exist.');
    } 

    /*
     * Deleting item_ingrident
     */
    function remove($id)
    {
        $item_ingrident = $this->Item_ingrident_model->get_item_ingrident($id);

        // check if the item_ingrident exists before trying to delete it
        if(isset($item_ingrident['id']))
        {
            $this->Item_ingrident_model->delete_item_ingrident($id);
            redirect('item_ingrident/index');
        }
        else
            show_error('The item_ingrident you are trying to delete does not exist.');
    }
    
}
