<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Testominal extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Testominal_model');
    }

    /*
     * Listing of testominals
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('testominal/index?');
        $config['total_rows'] = $this->Testominal_model->get_all_testominals_count();
        $this->pagination->initialize($config);

        $data['testominal'] = $this->Testominal_model->get_all_testominals($params);

        $data['_view'] = 'testominal/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new testominal
     */
    function add()
    {
        if(isset($_POST) && count($_POST) > 0)
        {

            $config = array(
                'upload_path' => "./uploads/",
                'allowed_types' => "gif|jpg|png|jpeg|pdf",
                'overwrite' => TRUE,
                'max_size' => "2048000", // Can be set to particular file size , here it is 2 MB(2048 Kb)
                'max_height' => "2000",
                'max_width' => "3000",
                'encrypt_name' => TRUE
            );
            $this->load->library('upload', $config);
            if (  $this->upload->do_upload('image'))
            {
                $data = array('upload_data' => $this->upload->data());

                print_r($data);
            }
            else
            {

                $error = array('error' => $this->upload->display_errors());
                echo print_r($error);
            }

            $params = array(
                'title' => $this->input->post('title'),
                'image' => isset($_FILES['image'])?$_FILES['image']['name']:"default.jpg",
                'text' => $this->input->post('text'),
                'author' => $this->input->post('author'),
            );

            $testominal_id = $this->Testominal_model->add_testominal($params);
            redirect('testominal/index');
        }
        else
        {
            $data['_view'] = 'testominal/add';
            $this->load->view('layouts/main',$data);
        }
    }

    /*
     * Editing a testominal
     */
    function edit($id)
    {
        // check if the testominal exists before trying to edit it
        $data['testominal'] = $this->Testominal_model->get_testominal($id);
        $image=$data['testominal']['image'];

        $new_upload=false;
        if(isset($data['testominal']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)
            {

                if(isset($_FILES['image'])) {
                    $config = array(
                        'upload_path' => "./uploads/",
                        'allowed_types' => "gif|jpg|png|jpeg|pdf",
                        'overwrite' => TRUE,
                        'max_size' => "2048000", // Can be set to particular file size , here it is 2 MB(2048 Kb)
                        'max_height' => "2000",
                        'max_width' => "3000",
                        'encrypt_name' => TRUE
                    );
                    $this->load->library('upload', $config);
                    if ($this->upload->do_upload('image')) {
                        $data = array('upload_data' => $this->upload->data());
                        $new_upload=true;
                    } else {

                        $error = array('error' => $this->upload->display_errors());
                        echo print_r($error);
                    }
                }


                $params = array(
                    'title' => $this->input->post('title'),
                    'image' => ($new_upload==true)?$_FILES['image']['name']: $image,
                    'text' => $this->input->post('text'),
                    'author' => $this->input->post('author'),
                );

                $this->Testominal_model->update_testominal($id,$params);
                redirect('testominal/index');
            }
            else
            {
                $data['_view'] = 'testominal/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The testominal you are trying to edit does not exist.');
    }

    /*
     * Deleting testominal
     */
    function remove($id)
    {
        $testominal = $this->Testominal_model->get_testominal($id);

        // check if the testominal exists before trying to delete it
        if(isset($testominal['id']))
        {
            $this->Testominal_model->delete_testominal($id);
            redirect('testominal/index');
        }
        else
            show_error('The testominal you are trying to delete does not exist.');
    }

}

